 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/quiz_trivia", type: :request do
  # QuizTrivium. As you add validations to QuizTrivium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      QuizTrivium.create! valid_attributes
      get quiz_trivia_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      quiz_trivium = QuizTrivium.create! valid_attributes
      get quiz_trivium_url(quiz_trivium)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_quiz_trivium_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      quiz_trivium = QuizTrivium.create! valid_attributes
      get edit_quiz_trivium_url(quiz_trivium)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new QuizTrivium" do
        expect {
          post quiz_trivia_url, params: { quiz_trivium: valid_attributes }
        }.to change(QuizTrivium, :count).by(1)
      end

      it "redirects to the created quiz_trivium" do
        post quiz_trivia_url, params: { quiz_trivium: valid_attributes }
        expect(response).to redirect_to(quiz_trivium_url(QuizTrivium.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new QuizTrivium" do
        expect {
          post quiz_trivia_url, params: { quiz_trivium: invalid_attributes }
        }.to change(QuizTrivium, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post quiz_trivia_url, params: { quiz_trivium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested quiz_trivium" do
        quiz_trivium = QuizTrivium.create! valid_attributes
        patch quiz_trivium_url(quiz_trivium), params: { quiz_trivium: new_attributes }
        quiz_trivium.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the quiz_trivium" do
        quiz_trivium = QuizTrivium.create! valid_attributes
        patch quiz_trivium_url(quiz_trivium), params: { quiz_trivium: new_attributes }
        quiz_trivium.reload
        expect(response).to redirect_to(quiz_trivium_url(quiz_trivium))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        quiz_trivium = QuizTrivium.create! valid_attributes
        patch quiz_trivium_url(quiz_trivium), params: { quiz_trivium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested quiz_trivium" do
      quiz_trivium = QuizTrivium.create! valid_attributes
      expect {
        delete quiz_trivium_url(quiz_trivium)
      }.to change(QuizTrivium, :count).by(-1)
    end

    it "redirects to the quiz_trivia list" do
      quiz_trivium = QuizTrivium.create! valid_attributes
      delete quiz_trivium_url(quiz_trivium)
      expect(response).to redirect_to(quiz_trivia_url)
    end
  end
end
